require('dotenv').config();
const express = require('express');
const mongoose = require('mongoose');
const helmet = require('helmet');
const cors = require('cors');
const rateLimit = require('express-rate-limit');
const passport = require('passport');
const session = require('express-session');
const authRoutes = require('./routes/auth');
const adminRoutes = require('./routes/admin');
const orderRoutes = require('./routes/order');
const auditMiddleware = require('./middleware/activityLogger');
const bodyParser = require('body-parser');
const app = express();
app.use(helmet());
app.use(express.json());
app.use(bodyParser.json({limit: '10mb'}));
app.use(cors({ origin: true, credentials: true }));
app.use(rateLimit({ windowMs: 60*1000, max: 200 }));
mongoose.connect(process.env.MONGO_URI).then(()=> console.log('Mongo connected')).catch(err=>{ console.error(err); process.exit(1); });
app.use(session({ secret: process.env.JWT_SECRET||'dev', resave:false, saveUninitialized:false }));
app.use(passport.initialize());
app.use(passport.session());
require('./routes/passport-setup')(passport);
app.use('/auth', authRoutes);
app.use('/api/admin', adminRoutes);
app.use('/api/order', orderRoutes);
app.use(auditMiddleware);
const PORT = process.env.PORT || 4000;
app.listen(PORT, ()=> console.log('Server running on', PORT));
